# Generated by Django 5.0.7 on 2024-08-10 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0009_joke_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['tag']},
        ),
    ]
